server:
  port: 7001

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己。
    fetch-registry: false         #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
  service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        #单机版配置设置与Eureka Server交互的地址查询服务
    #和注册服务都需要依赖这个地址。

    #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/        #集群配置，在此之前要修改C:\Windows\System32\drivers\etc路径下的hosts文件
    #127.0.0.1  eureka7001.com
    #127.0.0.1  eureka7002.com
    #127.0.0.1  eureka7003.com
