
server:
  port: 3344

spring:
  application:
    name:  lymcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nocence/lymcloud-config.git #GitHub\u4E0A\u9762\u7684git\u4ED3\u5E93\u540D\u5B57

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: config-3344.com
    prefer-ip-address: true